name: Build Changes
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the mod
        run: |
          export PATH=$ANDROID_HOME/build-tools/32.0.0:$PATH
          lein do uberjar, dex

      - uses: actions/upload-artifact@v2
        with:
          name: crescendo (zipped)
          path: |
            target/crescendo-*-android.jar
            target/crescendo-*-standalone.jar
