name: Build Changes
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the mod
        run: lein uberjar

      - uses: actions/upload-artifact@v2
        with:
          name: crescendo (zipped)
          path: target/uberjar/crescendo-*-standalone.jar
